kind: Job
apiVersion: batch/v1
metadata:
  name: nginx-job
  namespace: nginx
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: nginx-job
      labels:
        app: batch-task
    spec:
      containers:
        - name: batch-container
          image: busybox:latest  # it is used for only run the command
          command: ["sh","-c","echo hello && sleep 10"]
      restartPolicy: Never
