kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apache-manager
  namespace: apache
rules:
  - apiGroups: ["","apps","authorization.k8s.io","batch"]
    resources: ["deployment","pods","service"]
    verbs: ["get","apply","delete","watch","create","patch"]

